package com.deepika.postpartum.expensetracker.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * Expense Entity / Model Class.

 * Represents a single expense record in the system.

 * Responsibilities:
 * - Stores expense data
 * - Represents database table row
 * - Provides getters and setters
 * - Supports object comparison

 * Table Mapping Example:

 * expense
 * -----------------------------
 * id
 * person_type
 * expense_type
 * amount
 * description
 * expense_date

 * Design Notes:
 * - Uses BigDecimal for precise financial calculations
 * - Uses LocalDate from Java Time API
 * - equals() and hashCode() based on ID
 */
public class Expense {

    /**
     * Formatter used ONLY for displaying date.
     * Internal storage remains ISO format (yyyy-MM-dd).
     */
    private static final DateTimeFormatter DISPLAY_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    // ================= FIELDS =================

    /**
     * Unique identifier for each expense.
     * Generated by database.
     */
    private Long id;

    /**
     * Indicates whether expense belongs to:
     * MOTHER or BABY.
     */
    private PersonType personType;

    /**
     * Category of expense.
     * Example:
     * FOOD, MEDICINE, DIAPER, etc.
     */
    private ExpenseType expenseType;

    /**
     * Amount spent.
     * Uses BigDecimal for financial accuracy.
     */
    private BigDecimal expenseAmount;

    /**
     * Optional description or notes.
     */
    private String description;

    /**
     * Date when expense occurred.
     */
    private LocalDate expenseDate;

    // ================= CONSTRUCTORS =================

    /**
     * Default Constructor.

     * Used when:
     * - Creating empty object
     * - Frameworks populate fields later
     */
    public Expense() {
    }

    /**
     * Parameterized Constructor.

     * Used when:
     * Creating a new expense before saving to database.

     * ID is not included because:
     * Database generates it automatically.
     */
    public Expense(
            PersonType personType,
            ExpenseType expenseType,
            BigDecimal expenseAmount,
            String description,
            LocalDate expenseDate) {

        this.personType = personType;
        this.expenseType = expenseType;
        this.expenseAmount = expenseAmount;
        this.description = description;
        this.expenseDate = expenseDate;
    }

    /**
     * Full Constructor.

     * Used when:
     * Retrieving data from database.
     */
    public Expense(
            Long id,
            PersonType personType,
            ExpenseType expenseType,
            BigDecimal expenseAmount,
            String description,
            LocalDate expenseDate) {

        this.id = id;
        this.personType = personType;
        this.expenseType = expenseType;
        this.expenseAmount = expenseAmount;
        this.description = description;
        this.expenseDate = expenseDate;
    }

    // ================= GETTERS & SETTERS =================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public PersonType getPersonType() {
        return personType;
    }

    public void setPersonType(PersonType personType) {
        this.personType = personType;
    }

    public ExpenseType getExpenseType() {
        return expenseType;
    }

    public void setExpenseType(ExpenseType expenseType) {
        this.expenseType = expenseType;
    }

    public BigDecimal getExpenseAmount() {
        return expenseAmount;
    }

    public void setExpenseAmount(BigDecimal expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getExpenseDate() {
        return expenseDate;
    }

    public void setExpenseDate(LocalDate expenseDate) {
        this.expenseDate = expenseDate;
    }

    // ================= toString =================

    /**
     * Provides readable output when printing object.

     * Example:
     * Expense{id=1, personType=MOTHER, expenseType=FOOD,
     * expenseAmount=250.00, expenseDate=10-02-2026}
     */
    @Override
    public String toString() {

        String formattedDate = null;

        if (expenseDate != null) {
            formattedDate = expenseDate.format(DISPLAY_DATE_FORMATTER);
        }

        return "Expense{" +
                "id=" + id +
                ", personType=" + personType +
                ", expenseType=" + expenseType +
                ", expenseAmount=" + expenseAmount +
                ", expenseDate=" + formattedDate +
                '}';
    }

    // ================= equals =================

    /**
     * Custom equality check.

     * Two Expense objects are considered equal
     * if they have the same ID.
     */
    @Override
    public boolean equals(Object o) {

        if (this == o) return true;

        if (!(o instanceof Expense))
            return false;

        Expense expense = (Expense) o;

        return Objects.equals(
                id,
                expense.id
        );
    }

    // ================= hashCode =================

    /**
     * Generates hash code based on ID.
     * Required when equals() is overridden.
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

}